In [1]:
import tensorflow as tf

In [13]:
# init tensors
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
x = tf.constant([
    [1,2,3],
    [4,5,6]
])
x = tf.ones((4,4))
x = tf.eye(3) # "I" for identity matrix (eye)
x = tf.random.normal((3,3), mean=0, stddev=1)
x = tf.random.uniform((3,3), minval=0, maxval=1)
x = tf.cast(x, dtype=tf.float16)
x

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[0.7495, 0.753 , 0.986 ],
       [0.9106, 0.4287, 0.8003],
       [0.4568, 0.8115, 0.1809]], dtype=float16)>

In [27]:
# mathematical operations
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.add(x, y)
z = tf.tensordot(x, y, axes=1)
z = tf.reduce_sum(x*y, axis=0)

z

<tf.Tensor: shape=(), dtype=int32, numpy=32>

In [31]:
# indexing
x = tf.constant([0, 1, 2, 3, 4, 5])
x[1:3]
x[::2]

indices = tf.constant([0])
tf.gather(x, indices)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([0], dtype=int32)>

In [37]:
# reshaping
x = tf.range(9)
tf.reshape(x, (3, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>